#!/bin/sh
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, you may need to GET a POSIX shell, or have this script
#       executed by bash  or similar.
#
#   (2) The slickness of a POSIX shell will often expand "...$(expr 1 + 1)..." to
#       "...2..." which is FINE because expr returns "2".  It will NOT expand
#       UKnum=`expr 1 + 1` to "num=2" if used as a condition, since the Command
#       substitution is only done within $(...), but not within unquoted strings.
#
#   (3) Each term of the command line is now quoted using '"...`...`..."' to
#       protect variables and backslashes. This method does not work for all
#       shells, in which case you should use single quotes and do the variable
#       expansion manually or use the xpg_echo-fallback at the top of the file.
#
#   (4) "greadlink" does not work on macOS when used in the context of "...$(greadlink
#       ...)...", but does work when used as it is here.
#
#   START Local customization
#   In order to add a custom command, add it before the $scriptName line.
#   e.g. to add custom JVM options:
#
#   Optionally, set the following variables before running the script:
#   APP_HOME - location of your app that should be used instead of "SCRIPT_DIR"
#   APP_NAME - the name of app to display in the command line
#   APP_ARGS - parameters passed through to the application
#   JAVA_HOME - location of the java installation to use
#   JAVA_OPTS - parameters passed to the Java VM
#   GRADLE_USER_HOME - location of gradle user home
#       DEFAULT VALUE is ~/.gradle
#
#   START Local customization
#   Notice that you can use variables here that are defined later in the script

[ -n "$JAVA_HOME" ] && java_exe="$JAVA_HOME/bin/java"
[ -z "$java_exe" ] && java_exe="java"
[ -n "$GRADLE_USER_HOME" ] && gradle_user_home="$GRADLE_USER_HOME"

# determine gradle binary location
found=0
progloc="$(cd "$(dirname "$0")"; pwd)"

# Store Setting in variable, as it could be user overridden
app_args="$@"

# Collect all arguments for the java command, following the shell quoting and substitution rules
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        "-Dorg.gradle.user.home=${gradle_user_home}" \
        -classpath "$classpath" \
        org.gradle.wrapper.GradleWrapperMain \
        "$app_args"

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
    cd "$(dirname "$0")" || exit 1
fi

# Buscar el jar del wrapper
exec "$java_exe" "$@"
